# Generated by Django 4.2.30 on 2026-09-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0003_alter_nextofkin_phone_number_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_session_student',
        ),
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_class_session',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancestatus'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='is_present',
            field=models.BooleanField(default=False, help_text='Whether this status counts as present for reporting'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for this status (e.g., 1.0 for present, 0.5 for late)', max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('class_instance', 'session_date', 'session_number')},
        ),
    ]
