from rest_framework import serializers
from .models import Student, NextOfKin, StudentDocument
from apps.accounts.models import User


class UserSerializer(serializers.ModelSerializer):
    """Serializer for User model."""
    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name', 'email']
        read_only_fields = fields


class NextOfKinSerializer(serializers.ModelSerializer):
    """Serializer for NextOfKin model."""
    class Meta:
        model = NextOfKin
        fields = '__all__'
        read_only_fields = ['id', 'created_at', 'updated_at']


class StudentDocumentSerializer(serializers.ModelSerializer):
    """Serializer for StudentDocument model."""
    uploaded_by = UserSerializer(read_only=True)
    verified_by = UserSerializer(read_only=True)

    class Meta:
        model = StudentDocument
        fields = '__all__'
        read_only_fields = ['id', 'uploaded_at', 'file_size', 'uploaded_by', 'verified_by', 'verified_at']


class StudentSerializer(serializers.ModelSerializer):
    """Serializer for Student model."""
    next_of_kin = NextOfKinSerializer(read_only=True)
    documents = StudentDocumentSerializer(many=True, read_only=True)
    created_by = UserSerializer(read_only=True)
    updated_by = UserSerializer(read_only=True)

    class Meta:
        model = Student
        fields = '__all__'
        read_only_fields = ['id', 'student_id', 'date_created', 'date_updated', 'created_by', 'updated_by']

    def validate_national_id_passport(self, value):
        """Ensure national ID/passport is unique."""
        queryset = Student.objects.filter(national_id_passport=value)
        if self.instance:
            queryset = queryset.exclude(pk=self.instance.pk)
        if queryset.exists():
            raise serializers.ValidationError("A student with this national ID/passport already exists.")
        return value

    def validate_phone_number(self, value):
        """Validate phone number format."""
        import re
        if not re.match(r'^\+?1?\d{9,15}$', value):
            raise serializers.ValidationError("Enter a valid phone number.")
        return value


class StudentRegistrationSerializer(serializers.ModelSerializer):
    """Serializer for student registration with simplified fields."""
    next_of_kin = NextOfKinSerializer(required=False)

    class Meta:
        model = Student
        fields = [
            'first_name', 'last_name', 'gender', 'date_of_birth', 'nationality',
            'national_id_passport', 'phone_number', 'email', 'address',
            'previous_education', 'english_level', 'previous_ielts_attempts',
            'target_band', 'intended_destination', 'photo', 'next_of_kin'
        ]

    def create(self, validated_data):
        """
        Create a new student with optional next of kin.
        The student_id will be automatically generated by the model's save method.
        """
        next_of_kin_data = validated_data.pop('next_of_kin', None)

        # Create student - student_id will be generated automatically
        student = Student.objects.create(**validated_data)

        # Create next of kin if provided
        if next_of_kin_data:
            NextOfKin.objects.create(student=student, **next_of_kin_data)

        return student

    def validate_national_id_passport(self, value):
        """Ensure national ID/passport is unique."""
        queryset = Student.objects.filter(national_id_passport=value)
        if queryset.exists():
            raise serializers.ValidationError("A student with this national ID/passport already exists.")
        return value

    def validate_phone_number(self, value):
        """Validate phone number format."""
        import re
        if not re.match(r'^\+?1?\d{9,15}$', value):
            raise serializers.ValidationError("Enter a valid phone number.")
        return value