# Generated by Django 4.2.30 on 2026-09-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_nextofkin_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='target_band',
        ),
    ]
